[server]
enableStaticServing = true

[[theme.fontFaces]]
family="figtree"
url="app/static/Figtree-VariableFont_wght.ttf"
style="normal"
[[theme.fontFaces]]
family="figtree"
url="app/static/Figtree-Italic-VariableFont_wght.ttf"
style="italic"

[theme]
font="figtree"
headingFont="figtree"

base="light"
backgroundColor="#F7F7F8"
secondaryBackgroundColor="#FFFFFF"
primaryColor="#FF671D"
textColor="#1A1B1E"
linkColor="#E05510"
